language: php

php:
   - 5.3
   - 5.4
   - 5.5

env:
   global:
      - secure: "CP5N7I2yCfOyL4is6qgICX3LuNp5OTLx39XNKLKfwyiCanHal80EZFE+nGVNe9mYuk27Iccdaw0bOZJyMp6je9XsfBTHqpnZwZiEYO7LbhJr8Er545IcKiqxNuyJltHoru8BwfFd5bgtEl8qzJw9dyTpoepIGp1VY7/TLtziAso="
   matrix:
      - SYMFONY_VERSION=2.3.*
      - SYMFONY_VERSION=2.4.*

before_script:
   - composer self-update
   - sh -c "if $TRAVIS_SECURE_ENV_VARS; then composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi"
   - composer require --dev symfony/symfony:${SYMFONY_VERSION}

script:
   - bin/phpunit --coverage-text
   - bin/phpcs --standard=vendor/apnet/coding-standard/src/Apnet src
